
// Login
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Subscriptions
export const GET_SUBSCRIPTIONS_BEGIN = 'GET_SUBSCRIPTIONS_BEGIN';
export const GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_FAILURE = 'GET_SUBSCRIPTIONS_FAILURE';

// Usage
export const GET_USAGE_BEGIN = 'GET_USAGE_BEGIN';
export const GET_USAGE_SUCCESS = 'GET_USAGE_SUCCESS';
export const GET_USAGE_FAILURE = 'GET_USAGE_FAILURE';

// Virtual Machine Details
export const GET_VIRTUAL_MACHINE_DETAIL_BEGIN = 'GET_VIRTUAL_MACHINE_DETAIL_BEGIN';
export const GET_VIRTUAL_MACHINE_DETAIL_SUCCESS = 'GET_VIRTUAL_MACHINE_DETAIL_SUCCESS';
export const GET_VIRTUAL_MACHINE_DETAIL_FAILURE = 'GET_VIRTUAL_MACHINE_DETAIL_FAILURE';

// Virtual Machines
export const GET_VIRTUAL_MACHINES_BEGIN = 'GET_VIRTUAL_MACHINES_BEGIN';
export const GET_VIRTUAL_MACHINES_SUCCESS = 'GET_VIRTUAL_MACHINES_SUCCESS';
export const GET_VIRTUAL_MACHINES_FAILURE = 'GET_VIRTUAL_MACHINES_FAILURE';
